name: BUILD HMMER CONTAINER

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create Docker Hub Repository
        uses: peter-evans/create-dockerhub-repository@v1
        with:
          namespace: ${{ secrets.DOCKERHUB_USERNAME }}
          repository: 'hmmer'
          private: false
          description: 'HMMER Docker image'
          token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./HMMER
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hmmer:latest 
